# Generated by Django 3.1.7 on 2021-04-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date_of_file_upload', models.DateField()),
                ('file', models.FileField(upload_to='File/file/')),
            ],
        ),
        migrations.DeleteModel(
            name='files',
        ),
        migrations.RemoveField(
            model_name='webappuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='webappuser',
            name='contact_num',
        ),
    ]
