# Generated by Django 3.1.7 on 2021-04-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210417_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filename',
        ),
    ]
